//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAlmacenFormAsync.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pale", Namespace="http://schemas.datacontract.org/2004/07/GestionAlmacen")]
    [System.SerializableAttribute()]
    public partial class Pale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Extra.Productos ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeCreacion {
            get {
                return this.FechaDeCreacionField;
            }
            set {
                if ((this.FechaDeCreacionField.Equals(value) != true)) {
                    this.FechaDeCreacionField = value;
                    this.RaisePropertyChanged("FechaDeCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((this.PesoField.Equals(value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Extra.Productos Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((this.ProductoField.Equals(value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ubicacion", Namespace="http://schemas.datacontract.org/2004/07/GestionAlmacen")]
    [System.SerializableAttribute()]
    public partial class Ubicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasilloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Altura {
            get {
                return this.AlturaField;
            }
            set {
                if ((object.ReferenceEquals(this.AlturaField, value) != true)) {
                    this.AlturaField = value;
                    this.RaisePropertyChanged("Altura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Columna {
            get {
                return this.ColumnaField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnaField, value) != true)) {
                    this.ColumnaField = value;
                    this.RaisePropertyChanged("Columna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mano {
            get {
                return this.ManoField;
            }
            set {
                if ((object.ReferenceEquals(this.ManoField, value) != true)) {
                    this.ManoField = value;
                    this.RaisePropertyChanged("Mano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pasillo {
            get {
                return this.PasilloField;
            }
            set {
                if ((object.ReferenceEquals(this.PasilloField, value) != true)) {
                    this.PasilloField = value;
                    this.RaisePropertyChanged("Pasillo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGestionAlmacen")]
    public interface IGestionAlmacen {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/AltaPale", ReplyAction="http://tempuri.org/IGestionAlmacen/AltaPaleResponse")]
        string AltaPale(GestionAlmacenFormAsync.ServiceReference1.Pale pale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/AltaPale", ReplyAction="http://tempuri.org/IGestionAlmacen/AltaPaleResponse")]
        System.Threading.Tasks.Task<string> AltaPaleAsync(GestionAlmacenFormAsync.ServiceReference1.Pale pale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/BajaPale", ReplyAction="http://tempuri.org/IGestionAlmacen/BajaPaleResponse")]
        string BajaPale(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/BajaPale", ReplyAction="http://tempuri.org/IGestionAlmacen/BajaPaleResponse")]
        System.Threading.Tasks.Task<string> BajaPaleAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/UbicarPale", ReplyAction="http://tempuri.org/IGestionAlmacen/UbicarPaleResponse")]
        void UbicarPale(string codigo, GestionAlmacenFormAsync.ServiceReference1.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/UbicarPale", ReplyAction="http://tempuri.org/IGestionAlmacen/UbicarPaleResponse")]
        System.Threading.Tasks.Task UbicarPaleAsync(string codigo, GestionAlmacenFormAsync.ServiceReference1.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/RecuperarPale", ReplyAction="http://tempuri.org/IGestionAlmacen/RecuperarPaleResponse")]
        GestionAlmacenFormAsync.ServiceReference1.Pale RecuperarPale(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/RecuperarPale", ReplyAction="http://tempuri.org/IGestionAlmacen/RecuperarPaleResponse")]
        System.Threading.Tasks.Task<GestionAlmacenFormAsync.ServiceReference1.Pale> RecuperarPaleAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/GetUbicacionPale", ReplyAction="http://tempuri.org/IGestionAlmacen/GetUbicacionPaleResponse")]
        GestionAlmacenFormAsync.ServiceReference1.Ubicacion GetUbicacionPale(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/GetUbicacionPale", ReplyAction="http://tempuri.org/IGestionAlmacen/GetUbicacionPaleResponse")]
        System.Threading.Tasks.Task<GestionAlmacenFormAsync.ServiceReference1.Ubicacion> GetUbicacionPaleAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/fetchPales", ReplyAction="http://tempuri.org/IGestionAlmacen/fetchPalesResponse")]
        GestionAlmacenFormAsync.ServiceReference1.Pale[] fetchPales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAlmacen/fetchPales", ReplyAction="http://tempuri.org/IGestionAlmacen/fetchPalesResponse")]
        System.Threading.Tasks.Task<GestionAlmacenFormAsync.ServiceReference1.Pale[]> fetchPalesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionAlmacenChannel : GestionAlmacenFormAsync.ServiceReference1.IGestionAlmacen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionAlmacenClient : System.ServiceModel.ClientBase<GestionAlmacenFormAsync.ServiceReference1.IGestionAlmacen>, GestionAlmacenFormAsync.ServiceReference1.IGestionAlmacen {
        
        public GestionAlmacenClient() {
        }
        
        public GestionAlmacenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionAlmacenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAlmacenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAlmacenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AltaPale(GestionAlmacenFormAsync.ServiceReference1.Pale pale) {
            return base.Channel.AltaPale(pale);
        }
        
        public System.Threading.Tasks.Task<string> AltaPaleAsync(GestionAlmacenFormAsync.ServiceReference1.Pale pale) {
            return base.Channel.AltaPaleAsync(pale);
        }
        
        public string BajaPale(string codigo) {
            return base.Channel.BajaPale(codigo);
        }
        
        public System.Threading.Tasks.Task<string> BajaPaleAsync(string codigo) {
            return base.Channel.BajaPaleAsync(codigo);
        }
        
        public void UbicarPale(string codigo, GestionAlmacenFormAsync.ServiceReference1.Ubicacion ubicacion) {
            base.Channel.UbicarPale(codigo, ubicacion);
        }
        
        public System.Threading.Tasks.Task UbicarPaleAsync(string codigo, GestionAlmacenFormAsync.ServiceReference1.Ubicacion ubicacion) {
            return base.Channel.UbicarPaleAsync(codigo, ubicacion);
        }
        
        public GestionAlmacenFormAsync.ServiceReference1.Pale RecuperarPale(string codigo) {
            return base.Channel.RecuperarPale(codigo);
        }
        
        public System.Threading.Tasks.Task<GestionAlmacenFormAsync.ServiceReference1.Pale> RecuperarPaleAsync(string codigo) {
            return base.Channel.RecuperarPaleAsync(codigo);
        }
        
        public GestionAlmacenFormAsync.ServiceReference1.Ubicacion GetUbicacionPale(string codigo) {
            return base.Channel.GetUbicacionPale(codigo);
        }
        
        public System.Threading.Tasks.Task<GestionAlmacenFormAsync.ServiceReference1.Ubicacion> GetUbicacionPaleAsync(string codigo) {
            return base.Channel.GetUbicacionPaleAsync(codigo);
        }
        
        public GestionAlmacenFormAsync.ServiceReference1.Pale[] fetchPales() {
            return base.Channel.fetchPales();
        }
        
        public System.Threading.Tasks.Task<GestionAlmacenFormAsync.ServiceReference1.Pale[]> fetchPalesAsync() {
            return base.Channel.fetchPalesAsync();
        }
    }
}
